#!/bin/bash
### ---
### name: 'ASSEMBLY_SNPS_SCALABLE:CLUSTERED_SNP_TREE:SKA_BUILD (cluster_cluster_1)'
### container: 'quay.io/biocontainers/ska2:0.3.7--h4349ce8_2'
### outputs:
### - 'cluster_1.skf'
### - 'versions.yml'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status grep -E 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | grep -E 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    printf "%s\n" \
        "%mem=${nxf_stat_ret[1]}" \
        "vmem=${nxf_stat_ret[2]}" \
        "rss=${nxf_stat_ret[3]}" \
        "peak_vmem=${nxf_stat_ret[4]}" \
        "peak_rss=${nxf_stat_ret[5]}" \
        "vol_ctxt=${nxf_stat_ret[6]}" \
        "inv_ctxt=${nxf_stat_ret[7]}" >> "$trace_file" || >&2 echo "Error: Failed to append to file: $trace_file"
}

nxf_write_trace() {
    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /bin/bash -euo pipefail /home/phemarajata/wf-assembly-snps-final/work/af/d19030faac8af95be93ef16ae7e8a9/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local cpu_model=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local cpu_model=$(< /proc/cpuinfo grep '^model name' | head -n 1 | awk 'BEGIN{FS="\t: "} { print $2 }')
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /bin/bash -euo pipefail /home/phemarajata/wf-assembly-snps-final/work/af/d19030faac8af95be93ef16ae7e8a9/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}
nxf_container_env() {
cat << EOF
export PYTHONNOUSERSITE="1"
export R_PROFILE_USER="/.Rprofile"
export R_ENVIRON_USER="/.Renviron"
export JULIA_DEPOT_PATH="/usr/local/share/julia"
export PATH="\$PATH:/home/phemarajata/wf-assembly-snps-final/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/phemarajata/wf-assembly-snps-final/work/af/d19030faac8af95be93ef16ae7e8a9/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 2048 --memory 4096m -e "NXF_TASK_WORKDIR" -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /home/phemarajata/wf-assembly-snps-final:/home/phemarajata/wf-assembly-snps-final -w "$NXF_TASK_WORKDIR" --name $NXF_BOXID quay.io/biocontainers/ska2:0.3.7--h4349ce8_2 /bin/bash -c "eval $(nxf_container_env); /bin/bash -euo pipefail /home/phemarajata/wf-assembly-snps-final/work/af/d19030faac8af95be93ef16ae7e8a9/.command.run nxf_trace"
}

nxf_stage() {
    true
    # stage input files
    rm -f GCF_014712955_1_Laos.fasta
    rm -f GCA_963566695_1.fasta
    rm -f GCA_963572615_1.fasta
    rm -f GCF_025847905_1_Viet_Nam.fasta
    rm -f GCF_000774495_1_Australia.fasta
    rm -f GCA_963571975_1.fasta
    rm -f GCF_001207785_2_Malaysia.fasta
    rm -f GCA_963565565_1.fasta
    rm -f GCF_003268105_1_Viet_Nam.fasta
    rm -f GCA_963566635_1.fasta
    rm -f GCF_002110985_1_USA_Puerto_Rico.fasta
    rm -f GCA_963570025_1.fasta
    rm -f GCA_963573225_1.fasta
    rm -f GCF_014713085_1_Laos.fasta
    rm -f GCA_963569365_1.fasta
    rm -f GCA_963569795_1.fasta
    rm -f GCF_014712895_1_Laos.fasta
    rm -f GCA_963568785_1.fasta
    rm -f GCA_963566475_1.fasta
    rm -f GCA_963566765_1.fasta
    rm -f GCF_002111145_1_USA_Arizona_ex_Costa_Rica.fasta
    rm -f GCF_000773235_1_Australia.fasta
    rm -f GCF_003268075_1_Viet_Nam.fasta
    rm -f IE-0001.fasta
    rm -f GCA_963569325_1.fasta
    rm -f GCA_963566175_1.fasta
    rm -f GCF_014712915_1_Laos.fasta
    rm -f GCA_963573095_1.fasta
    rm -f GCA_963566495_1.fasta
    rm -f GCF_002110925_1_USA_Texas.fasta
    rm -f GCF_014712775_1_Laos.fasta
    rm -f GCF_014712935_1_Laos.fasta
    rm -f GCA_963565485_1.fasta
    rm -f GCA_963568055_1.fasta
    rm -f GCF_009827035_1_Viet_Nam.fasta
    rm -f GCA_963568885_1.fasta
    rm -f GCA_963567325_1.fasta
    rm -f GCA_963571475_1.fasta
    rm -f GCA_963569685_1.fasta
    rm -f GCA_963567935_1.fasta
    rm -f GCA_963571005_1.fasta
    rm -f GCA_963566625_1.fasta
    rm -f GCA_963568705_1.fasta
    rm -f GCA_963569645_1.fasta
    rm -f GCA_963566085_1.fasta
    rm -f GCA_963570105_1.fasta
    rm -f GCF_014712835_1_Laos.fasta
    rm -f GCA_963566855_1.fasta
    rm -f GCA_963570575_1.fasta
    rm -f GCA_963571055_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/c5/fffe7c8d3d3983200a548b67fa5305/inputfiles/GCF_014712955_1_Laos.fasta GCF_014712955_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/91/edb2a85b64b7ab79a6516a4a47c436/inputfiles/GCA_963566695_1.fasta GCA_963566695_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/7f/f5789af341dacc6bf9686d578e2130/inputfiles/GCA_963572615_1.fasta GCA_963572615_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e9/5f55ab553af930315f0ca8d9649847/inputfiles/GCF_025847905_1_Viet_Nam.fasta GCF_025847905_1_Viet_Nam.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/a2/e08a5ecef3e568ad227be4afa82e87/inputfiles/GCF_000774495_1_Australia.fasta GCF_000774495_1_Australia.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/a9/8f2789b3991d987792f9bcc17b5784/inputfiles/GCA_963571975_1.fasta GCA_963571975_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/b0/d97b19785189d45ff7316e6181f64e/inputfiles/GCF_001207785_2_Malaysia.fasta GCF_001207785_2_Malaysia.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/84/706a2ddae67d15bd1ade1b54d34ea9/inputfiles/GCA_963565565_1.fasta GCA_963565565_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/4f/e168f931af1343a1f2bab82d3ef035/inputfiles/GCF_003268105_1_Viet_Nam.fasta GCF_003268105_1_Viet_Nam.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/be/65d4a3369dd47105cc70f78c4cc35f/inputfiles/GCA_963566635_1.fasta GCA_963566635_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/b7/132118643aec01841cb75448734709/inputfiles/GCF_002110985_1_USA_Puerto_Rico.fasta GCF_002110985_1_USA_Puerto_Rico.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/21/cdacb56274b56ddbe5a3fb10baa130/inputfiles/GCA_963570025_1.fasta GCA_963570025_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/aa/090e051eb6bca068ebb598f7c935cb/inputfiles/GCA_963573225_1.fasta GCA_963573225_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/2a/166fd52a513b9f6153f09729068f44/inputfiles/GCF_014713085_1_Laos.fasta GCF_014713085_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/d5/9db79c44b6c46dab348271ab02acbc/inputfiles/GCA_963569365_1.fasta GCA_963569365_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/47/69b2e0f20a50646b6292b43b1fc6de/inputfiles/GCA_963569795_1.fasta GCA_963569795_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/24/90f149476ac942ec553d405dc5880a/inputfiles/GCF_014712895_1_Laos.fasta GCF_014712895_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e5/bf2c42f099360cf851c5089c55979b/inputfiles/GCA_963568785_1.fasta GCA_963568785_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/50/a47f8001f48a10f8403d33786e264e/inputfiles/GCA_963566475_1.fasta GCA_963566475_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e5/b6db7812061782c726d50269cb1dfe/inputfiles/GCA_963566765_1.fasta GCA_963566765_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/69/b020ad079e16900eb060ce2ce26ade/inputfiles/GCF_002111145_1_USA_Arizona_ex_Costa_Rica.fasta GCF_002111145_1_USA_Arizona_ex_Costa_Rica.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/d1/830d5f4819076b2124941a61a73efd/inputfiles/GCF_000773235_1_Australia.fasta GCF_000773235_1_Australia.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/fc/cec950ffbb62cea4dfa5c2cf294dd8/inputfiles/GCF_003268075_1_Viet_Nam.fasta GCF_003268075_1_Viet_Nam.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/64/02b4911a44904e0fd0b6e77ceb2eee/inputfiles/IE-0001.fasta IE-0001.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/da/b76a8fb8deb5b00e17538225ea2075/inputfiles/GCA_963569325_1.fasta GCA_963569325_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/86/91c28607c8ddff04eafba3820407f7/inputfiles/GCA_963566175_1.fasta GCA_963566175_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/53/d30afe6ccf38ff14603f9df8af68be/inputfiles/GCF_014712915_1_Laos.fasta GCF_014712915_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/55/3bd4f37c35dbac576c33323c10a720/inputfiles/GCA_963573095_1.fasta GCA_963573095_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/61/9564f6329ea017c56d6f3e575d1a80/inputfiles/GCA_963566495_1.fasta GCA_963566495_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/24/40685c56daf92bb9b8d1c4c80532a4/inputfiles/GCF_002110925_1_USA_Texas.fasta GCF_002110925_1_USA_Texas.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/cb/73bd1566afeda30a542f1b31f339e3/inputfiles/GCF_014712775_1_Laos.fasta GCF_014712775_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/80/37ccc3ab02e8e5d8e506f783965e72/inputfiles/GCF_014712935_1_Laos.fasta GCF_014712935_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/4d/003057056e4e712d31e17b8831a312/inputfiles/GCA_963565485_1.fasta GCA_963565485_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/99/57e42c9206c5bbae6c021bb61c1313/inputfiles/GCA_963568055_1.fasta GCA_963568055_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/97/c9a8edaa8828b75f5bfc8991539bf0/inputfiles/GCF_009827035_1_Viet_Nam.fasta GCF_009827035_1_Viet_Nam.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/2e/bd9ffc8b7dfa8a641ee064fdc3dcd1/inputfiles/GCA_963568885_1.fasta GCA_963568885_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/dc/7eb80c95c97f1cd08cf0a0ba032e6f/inputfiles/GCA_963567325_1.fasta GCA_963567325_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/79/2cb294e7434ec1c401bb52efc8cf64/inputfiles/GCA_963571475_1.fasta GCA_963571475_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/b8/843f5725fc690fd2d1c53eaad5a0a3/inputfiles/GCA_963569685_1.fasta GCA_963569685_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/b6/beb9427a9a60969dae14f4cdd72c3d/inputfiles/GCA_963567935_1.fasta GCA_963567935_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/77/d72c36448753048fbdb81d9469bad2/inputfiles/GCA_963571005_1.fasta GCA_963571005_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/7b/78357d14e38cd086a16cc34db46e57/inputfiles/GCA_963566625_1.fasta GCA_963566625_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/c0/2c70fb71bc2c8fd46f6d051c8f7d3e/inputfiles/GCA_963568705_1.fasta GCA_963568705_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/c7/d10797fcaf67f93a280495904e60eb/inputfiles/GCA_963569645_1.fasta GCA_963569645_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e5/045d36f994b2f8e88d7f180a3652cc/inputfiles/GCA_963566085_1.fasta GCA_963566085_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/c8/5fecfce01e50d3bf5d2dc5033494d1/inputfiles/GCA_963570105_1.fasta GCA_963570105_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/1e/648f6fad48ae99848d9f759aefa92e/inputfiles/GCF_014712835_1_Laos.fasta GCF_014712835_1_Laos.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/54/82b06efb5ec2fde00091c103e33c18/inputfiles/GCA_963566855_1.fasta GCA_963566855_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/88/2b715b9b741eb4cdef9898804263a6/inputfiles/GCA_963570575_1.fasta GCA_963570575_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ed/2e2994ebb984cc1c70c3d0c7295d20/inputfiles/GCA_963571055_1.fasta GCA_963571055_1.fasta
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/phemarajata/wf-assembly-snps-final/work/af/d19030faac8af95be93ef16ae7e8a9/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
