#!/bin/bash
### ---
### name: 'ASSEMBLY_SNPS_SCALABLE:CLUSTERED_SNP_TREE:SKA_BUILD (cluster_cluster_0)'
### container: 'quay.io/biocontainers/ska2:0.3.7--h4349ce8_2'
### outputs:
### - 'cluster_0.skf'
### - 'versions.yml'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status grep -E 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | grep -E 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    printf "%s\n" \
        "%mem=${nxf_stat_ret[1]}" \
        "vmem=${nxf_stat_ret[2]}" \
        "rss=${nxf_stat_ret[3]}" \
        "peak_vmem=${nxf_stat_ret[4]}" \
        "peak_rss=${nxf_stat_ret[5]}" \
        "vol_ctxt=${nxf_stat_ret[6]}" \
        "inv_ctxt=${nxf_stat_ret[7]}" >> "$trace_file" || >&2 echo "Error: Failed to append to file: $trace_file"
}

nxf_write_trace() {
    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /bin/bash -euo pipefail /home/phemarajata/wf-assembly-snps-final/work/0e/e89a3b51b89793b044a1756d01eb3c/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local cpu_model=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local cpu_model=$(< /proc/cpuinfo grep '^model name' | head -n 1 | awk 'BEGIN{FS="\t: "} { print $2 }')
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /bin/bash -euo pipefail /home/phemarajata/wf-assembly-snps-final/work/0e/e89a3b51b89793b044a1756d01eb3c/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}
nxf_container_env() {
cat << EOF
export PYTHONNOUSERSITE="1"
export R_PROFILE_USER="/.Rprofile"
export R_ENVIRON_USER="/.Renviron"
export JULIA_DEPOT_PATH="/usr/local/share/julia"
export PATH="\$PATH:/home/phemarajata/wf-assembly-snps-final/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/phemarajata/wf-assembly-snps-final/work/0e/e89a3b51b89793b044a1756d01eb3c/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 2048 --memory 4096m -e "NXF_TASK_WORKDIR" -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /home/phemarajata/wf-assembly-snps-final:/home/phemarajata/wf-assembly-snps-final -w "$NXF_TASK_WORKDIR" --name $NXF_BOXID quay.io/biocontainers/ska2:0.3.7--h4349ce8_2 /bin/bash -c "eval $(nxf_container_env); /bin/bash -euo pipefail /home/phemarajata/wf-assembly-snps-final/work/0e/e89a3b51b89793b044a1756d01eb3c/.command.run nxf_trace"
}

nxf_stage() {
    true
    # stage input files
    rm -f GCA_963564305_1.fasta
    rm -f GCA_963561915_1.fasta
    rm -f GCA_963564975_1.fasta
    rm -f GCA_963565015_1.fasta
    rm -f GCA_963561215_1.fasta
    rm -f ERS012307.fasta
    rm -f GCA_963561855_1.fasta
    rm -f ERS013346.fasta
    rm -f GCA_963561975_1.fasta
    rm -f GCA_963565125_1.fasta
    rm -f ERS012332.fasta
    rm -f GCA_963562795_1.fasta
    rm -f GCA_963563635_1.fasta
    rm -f ERS012306.fasta
    rm -f ERS013364.fasta
    rm -f GCA_963562615_1.fasta
    rm -f ERS012320.fasta
    rm -f GCA_963562965_1.fasta
    rm -f ERS013352.fasta
    rm -f GCA_963563155_1.fasta
    rm -f ERS012303.fasta
    rm -f ERS012358.fasta
    rm -f ERS012363.fasta
    rm -f GCA_963561435_1.fasta
    rm -f GCA_963563065_1.fasta
    rm -f GCA_963561835_1.fasta
    rm -f GCA_963561075_1.fasta
    rm -f GCA_963562695_1.fasta
    rm -f GCA_963565395_1.fasta
    rm -f ERS012312.fasta
    rm -f GCA_963560915_1.fasta
    rm -f GCA_963560945_1.fasta
    rm -f ERS012309.fasta
    rm -f GCA_963560675_1.fasta
    rm -f GCA_963563525_1.fasta
    rm -f ERS013343.fasta
    rm -f GCA_963560735_1.fasta
    rm -f GCA_963560585_1.fasta
    rm -f ERS012362.fasta
    rm -f ERS013348.fasta
    rm -f ERS012316.fasta
    rm -f GCA_963562655_1.fasta
    rm -f GCA_963564375_1.fasta
    rm -f ERS012365.fasta
    rm -f ERS013354.fasta
    rm -f ERS012330.fasta
    rm -f ERS012370.fasta
    rm -f ERS012313.fasta
    rm -f GCA_963563475_1.fasta
    rm -f GCA_963563715_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/6f/17136934e83c979fb9fca6fea5a0f6/inputfiles/GCA_963564305_1.fasta GCA_963564305_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/9d/c652c3d184e557e024543aea287545/inputfiles/GCA_963561915_1.fasta GCA_963561915_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e3/d587325cb5efe1bb98580904fbda07/inputfiles/GCA_963564975_1.fasta GCA_963564975_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/1c/e831ca5474b1912a6ffe2d4af75d3c/inputfiles/GCA_963565015_1.fasta GCA_963565015_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ad/83ffe4125a9760097d12632e597e31/inputfiles/GCA_963561215_1.fasta GCA_963561215_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/c2/dc56d18031bbec3fc77440ad32ed82/inputfiles/ERS012307.fasta ERS012307.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/78/4eff0117ab617c909a3d6dfb4d64e7/inputfiles/GCA_963561855_1.fasta GCA_963561855_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/47/106f1425a981adc2156da428391d1f/inputfiles/ERS013346.fasta ERS013346.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/f0/21c4136700d95a1ead9cf71f7192bc/inputfiles/GCA_963561975_1.fasta GCA_963561975_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/f5/f86e9232cdea7953dd0b5cb43d9d01/inputfiles/GCA_963565125_1.fasta GCA_963565125_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/6f/3336f749b14efa52fb5c950e1f5d6e/inputfiles/ERS012332.fasta ERS012332.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/18/373a60f484fadef123f73bcd2dfa3f/inputfiles/GCA_963562795_1.fasta GCA_963562795_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/af/deddfb02df459a3cae5979ad4d6eff/inputfiles/GCA_963563635_1.fasta GCA_963563635_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/a2/870826e2f0fb4e81e3b1ea97ae2a2a/inputfiles/ERS012306.fasta ERS012306.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ce/d40616126fd5c351617d993ea3a2f9/inputfiles/ERS013364.fasta ERS013364.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e4/e024177744dc14d12ba0d164f10db3/inputfiles/GCA_963562615_1.fasta GCA_963562615_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/05/cf59eea609425cb27285fa5e4d62c9/inputfiles/ERS012320.fasta ERS012320.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/45/1a1d54c8342c5dceb065cb28e4cbb4/inputfiles/GCA_963562965_1.fasta GCA_963562965_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ea/610bf867203fd513456c2c9c34b929/inputfiles/ERS013352.fasta ERS013352.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/d8/8002652df98531e6b8d4e6d75c6650/inputfiles/GCA_963563155_1.fasta GCA_963563155_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/85/30be7c0c27d1fb485f0ac897f36897/inputfiles/ERS012303.fasta ERS012303.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/6e/a1fd076ff563eafc58c77da00b1e7c/inputfiles/ERS012358.fasta ERS012358.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/0b/5ec845dd2f6166b76368f121818287/inputfiles/ERS012363.fasta ERS012363.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e2/252ec630cf2946dbefa576bdfea7bc/inputfiles/GCA_963561435_1.fasta GCA_963561435_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/65/68b84c455d132bfdc661312500ec99/inputfiles/GCA_963563065_1.fasta GCA_963563065_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/b3/8658573f1d5c74c6cb4c3b825899fc/inputfiles/GCA_963561835_1.fasta GCA_963561835_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/16/bc91645e412dc4e8e54f707c754f97/inputfiles/GCA_963561075_1.fasta GCA_963561075_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ba/2d890c552c7781918b92474eb8953c/inputfiles/GCA_963562695_1.fasta GCA_963562695_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/89/980466e2cc5077ab1dbaa445ca90aa/inputfiles/GCA_963565395_1.fasta GCA_963565395_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/3f/ddadf014c349c28019622b631427c2/inputfiles/ERS012312.fasta ERS012312.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/97/ba1401259a87236ddb03ebe933444f/inputfiles/GCA_963560915_1.fasta GCA_963560915_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/89/0663ad09901c56589d092720dc2a75/inputfiles/GCA_963560945_1.fasta GCA_963560945_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/14/8b4e9448099d4bc1ab4572117bbc4a/inputfiles/ERS012309.fasta ERS012309.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/56/10bc5f899fe969224309a80118b77c/inputfiles/GCA_963560675_1.fasta GCA_963560675_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/03/e583e33e8c4b490b295a2db5d210e4/inputfiles/GCA_963563525_1.fasta GCA_963563525_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/c6/c84401172716eecdee5ffe14cec4db/inputfiles/ERS013343.fasta ERS013343.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ff/d35f729a67f6d2fbf44d16ec643adc/inputfiles/GCA_963560735_1.fasta GCA_963560735_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/2f/9d495abcde3c9aee2781860d0510f6/inputfiles/GCA_963560585_1.fasta GCA_963560585_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e1/746bb73fe1db3ae546d9b6ae478adc/inputfiles/ERS012362.fasta ERS012362.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/ec/57abae1ed53baaadd64b37325d49fd/inputfiles/ERS013348.fasta ERS013348.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/5c/3459a85df90918abcdccbd3f230990/inputfiles/ERS012316.fasta ERS012316.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/11/5e0a8e937540dde9fe44bbecd343bd/inputfiles/GCA_963562655_1.fasta GCA_963562655_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/b5/b66e714b38eafd1f951f7bca2980fd/inputfiles/GCA_963564375_1.fasta GCA_963564375_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/43/aaa2c294a3ca248ff9178027de2a4c/inputfiles/ERS012365.fasta ERS012365.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/e0/f8cd041f8cbf0fafcff97b108386b2/inputfiles/ERS013354.fasta ERS013354.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/33/3074d261f366434d5e638ea7eb6b08/inputfiles/ERS012330.fasta ERS012330.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/48/333766b2417536b0d9ae00c8d1a024/inputfiles/ERS012370.fasta ERS012370.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/4e/d11525b2b71aa8ce6b7d8a5bc86ff1/inputfiles/ERS012313.fasta ERS012313.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/2d/031d1888a957dbab0a49096522fd3a/inputfiles/GCA_963563475_1.fasta GCA_963563475_1.fasta
    ln -s /home/phemarajata/wf-assembly-snps-final/work/63/45d0a4f8675e0eab77b8b466e1e626/inputfiles/GCA_963563715_1.fasta GCA_963563715_1.fasta
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/phemarajata/wf-assembly-snps-final/work/0e/e89a3b51b89793b044a1756d01eb3c/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
